### ISSUE TITLE
Reservation WhiteList

### ISSUE THREAD

**Issue by pulgamecanica** [pulgamecanica/42Rooms#2]
Hey Francisco!
Validate if a user belongs to the WhiteList to create a reservation.
You only have to do this one validation but it's not a simple validation, gl,  any question reach to me.
You can access the Room White list like this:
`room.white_lists` This will return an array of all the whitelists.
You can use C syntax no problem don't worry.
An example of how you can access the white lists.
```
def check_user
  i = 0
  while (room.white_lists[i])
    puts(room.white_lists[i])
    i += 1 
  end
end
```
💥  In ruby we use `+= 1` to increment, i++ doesn't exist

Your validation must go below this line:
https://github.com/pulgamecanica/42Rooms/blob/4b7401d9a9634f939b7ea581670fa0c0994035dc/app/models/reservation.rb#L5

DOCUMENTATION
https://guides.rubyonrails.org/active_record_validations.html

**Comment by PireXa** [comment]
int i = 0;
while(rooms.white_lists[I])
{
           if (user == rooms.white_lists[I])
                break;
           i++;
}
if (!(rooms.white_lists[I]))
           erro;
else
           nice;

**Comment by PireXa** [comment]
Não percebi como e que acedia aos users dentro das whitelists, mas acho que cheguei mais ou menos la, fiz em c so porque  dava pra pensar melhor

**Comment by pulgamecanica** [comment]
> int i = 0; while(rooms.white_lists[I]) { if (user == rooms.white_lists[I]) break; i++; } if (!(rooms.white_lists[I])) erro; else nice;
`
if (user == rooms.white_lists[I].user)`

**Comment by pulgamecanica** [comment]
Quando tens dúvidas de como acceder aos objetos (estruturas), basta consultar a imagem da base de dados:

<img width="1296" alt="Screen Shot 2022-05-11 at 23 34 02" src="https://user-images.githubusercontent.com/28810331/167958597-031e5e6e-5c4d-4478-989b-66dac202861c.png">

White List tem user_id. Por isso podes acceder a o integer user_id. Ou o objeto user.
