### ISSUE TITLE
Tolerance

### ISSUE THREAD

**Issue by pulgamecanica** [pulgamecanica/42Rooms#3]
Hello Rodrigo! :D
You must validate if a Reservation starts at least 10 minutes after the present time.
In Ruby, we can get the time with `Time.now`
And Time is a datatype. Type is comparable, so if you have two times **t1** & **t2** you can compare them` t1 == t2, t1 < t2` ; etc.

Validations must be first declared (this is mandatory).
And then they must be implemented as functions.
Your validation goes below this line.
https://github.com/pulgamecanica/42Rooms/blob/4b7401d9a9634f939b7ea581670fa0c0994035dc/app/models/reservation.rb#L5

DOCUMENTATION
https://edgeguides.rubyonrails.org/active_record_validations.html#custom-methods

**Comment by RodrigoEstrela** [comment]
def reservation_starts_at_least_10min_from_now
    if starts_at < Time.now + 600
      errors.add(:starts_at, "Reservation start time must be at least 10 min from now!")
    end
  end

**Comment by pulgamecanica** [comment]
`if starts_at < Time.now + 10.minutes` fica mais giro :)

**Comment by pulgamecanica** [comment]
https://github.com/pulgamecanica/42Rooms/commit/8ddbb7e996b64590e001b29b917318fc7111f6e9
